name: my_progress
description: A complete mobile application for daily consistency, DSA progress tracking, daily alarm paragraph challenge, and notes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  google_fonts: ^6.1.0
  audioplayers: ^6.1.0
  file_picker: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
