name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'

      - name: Get Dependencies
        run: |
          cd flutter_app
          flutter pub get

      - name: Build Release APK
        run: |
          cd flutter_app
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyProgress-Android-APK
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
